### ISSUE TITLE
Occasional maximum current spike.

### ISSUE THREAD

**Issue by xenoxclusive** [lbbrhzn/ocpp#1684]
The Current Import sensor `sensor.charger_current_import` occasionally spikes to maximum current draw without warning or reason.

I am using the recommended way to adjust the charging current as provided in https://github.com/lbbrhzn/ocpp/blob/main/docs/Charge_automation.md

I have a sensor titled `sensor.adjust_current` that I use as the `entity_charge_limit` that I can confirm does not go to the specified maximum current draw, shown below:

<img width="1407" height="504" alt="Image" src="https://github.com/user-attachments/assets/4e822798-3617-4aae-90e4-026eb5b2e032" />

During this time we can see that the `sensor.charger_current_import` sensor hits maximum 32a:

<img width="1394" height="503" alt="Image" src="https://github.com/user-attachments/assets/7666ea51-234b-4270-bfce-ee86634950e8" />

I can confirm that this isn't a graphical glitch as my power draw spikes at this very moment:

<img width="1409" height="537" alt="Image" src="https://github.com/user-attachments/assets/9aa7e45a-8247-4eea-8bce-925ca709aafc" />

**Comment by tmenguy** [comment]
@xenoxclusive what charger do you have? I do have 3 Wallbox Socket Pro.

**Comment by xenoxclusive** [comment]
> [@xenoxclusive](https://github.com/xenoxclusive) what charger do you have? I do have 3 Wallbox Socket Pro.

@tmenguy I have a wallbox pulsar. Great to hear this has been solved for you. I will be home shortly to charge my car and see how it looks for me.

**Comment by xenoxclusive** [comment]
Unfortunately this hasn't been fixed for me. 

I just enabled a charge and set the minimum 6a my charger supports and within a few minutes 32a had been hit twice. 

Very bad in my off-grid situation. I could hear my heat pump, dehumidifier and erv fans slow to a crawl momentarily as the voltage dropped due to having almost no generation today and everything running solely off the batteries (which can not take the 32a draw for very long).

**Comment by xenoxclusive** [comment]
I have never changed the max current value. It has always been 32 and I set the charge current as described in the docs as mentioned in my opening post.

As shown in those pictures in my most recent comment, charging started correctly at 6a and I did not change the set current once and there was a jump to 32a. More than one in fact but I only showed one.

**Comment by marsreis** [comment]
Since version 10, my ZJBeny momentary spikes every time I change the current (my automation does constantly). I have tried updating up to version 10.3 but the problem remained. I've rolled back to v9 and everything is perfect, and haven't bothered with the newer releases as I don't see this issue fix mentioned in the release notes.

**Comment by xenoxclusive** [comment]
> ok, sorry, didn't re-read everything ... but something of interest to me : the "https://github.com/lbbrhzn/ocpp/blob/main/docs/Charge_automation.md" approach gave me a "rejected" (hence I continue to use the set max). Have you done anything special to make it work on your Pulsar?

I have done nothing special. I have a 5 second delay when turning charge control on, otherwise my first attempt to change current says rejected, but after this it works perfectly.

I am perhaps having some success after executing the action `ocpp.clear_profile` but I need to do more testing once I get some sunshine. I will keep you updated.

**Comment by xenoxclusive** [comment]
So far so good. If it was a simple as clearing profile this entire time, I'll be rather annoyed at myself 🗡️

Any progress for you @tmenguy ?

**Comment by tmenguy** [comment]
Unfortunately for me it kept rejected ... I'll stay with the max for now. 
I'm using PowerShare ... perhaps by disabling it it will work...

**Comment by xenoxclusive** [comment]
Unfortunately my issue has not been resolved.

I have my inverters control software (SP LINK for my Selectronic) open, and I can see these spikes.

I have turned off all automations and only have the `ocpp.set_charge_rate` action being executed via HAs Actions section under Developer Tools.

I can set a current, and OCCASIONALLY (not always) I will see it briefly spike in SP LINK to maximum charge current before settling to the setting I set. What logs would you like me to provide to get to the bottom of this @jthun? And also, how do I provide them? Apologies.

Kind regards.

**Comment by tmenguy** [comment]
> Hi,
> 
> The way changing the max current for a single-connector charger works in the integration is that it first tries to send a `SetChargingProfile` with `ChargePointMaxProfile` message on connector 0 (the entire charger). That call might get rejected, which is normal. Many chargers do that. That’s probably what you’re seeing in the logs. The integration then tries to change the max current of the ongoing transaction on connector 1 by sending `SetChargingProfile` with `TxProfile` and then also sends `SetChargingProfile` with `TxDefaultProfile` to connector 1, to set the max current for future transactions.
> 
> These changes should take effect in the charger, unless there is another profile blocking/setting another value. You can fix that by running the `ocpp.clear_profile` action, with your charger id as `devid`.
> 
> Please post debug logs if your problems don’t go away, and I can take a closer look.

Thanks a lot , unfortunately what gets rejected is when I try to do myself (through an action) a `SetChargingProfile` with `TxProfile` (or `TxDefaultProfile`) to connector 1 , I get a rejection on this in the logs, it seems related to Wallbox blocking it (as seen in another post), and/or perhaps tied with the fact that I use power share (part of Wallbox HEMS)
